### ISSUE TITLE
wish: make i3-msg binary configurable

### ISSUE THREAD

**Issue by markstos** [gustavnikolaj/i3-run-or-raise#3]
This tool could use also be useful with the Sway window manager. It has a binary named `swaymsg` which appears to be compatible with `i3-msg`.

I'm not sure if you'd like to add support for this or prefer it was done in a fork.

**Comment by gustavnikolaj** [comment]
Do you know how much work this would be? I honestly don't and it's been a while since I have used this tool. I'll be happy to help facilitate this change as best I can, but I will probably need to rely on you to test and maybe implement it, if you're up for it. I am not using i3 myself anymore.

**Comment by markstos** [comment]
Thanks for the prompt response. To implement:
 
*  the contents of `bin/i3-run-or-raise` would be moved to a different file, like `lib/index.js`.  
* The contents of `bin/i3-run-or-raise` would do very little but set `wm:'i3'` as an option in a call into `lib/lindex.js`. 
*  A new file `bin/sway-run-or-raise` would be identical, but set `wm:'sway'`.
* Finally, in the places where `i3-msg` is hardcoded, this would be replaced with a variable, which would be set to `swaymsg` if the `wm:"sway"` option is set.

I also understand that you've moved on and don't have an incentive to implement this.

Perhaps someone else will find this Issue here and pick up the task to implement later. I may work on it myself if my evaluation of Sway continues to go well. 

If my ask, what window manager or desktop environment have you moved on to?

**Comment by gustavnikolaj** [comment]
Thanks for the outline. Turned out to be rather easy - I landed it as a PR #4 and made a prelease version (2.0.0-0 tagged next). I hope you'll take it for a spin and see if it works. I am pretty confident in the changes, but I don't have access to a system to test neither i3 nor sway on.

---

Wrt window manager - I actually moved back to Unity on Ubuntu a while ago. I got inspired by a colleague to try out a less customized setup - I had been running with i3 and a bastardized emacs setup emulating vim. It was a hard change, but I stuck with it and grew accustomed to it. 

Now, I have had to switch to macos for work, and I have a windows desktop at home, as well as a linux laptop. I have learned to live with the context switches and not be too annoyed with the different keyboard shortcuts etc when switching between them - but given the diversity of the platforms I work on, I have found myself relying (and caring) more on the applications I use being similar than the desktop environments.

If I have to be honest, I do miss it though. :-)

**Comment by markstos** [comment]
I'm trying it now. Thanks for the help!

I really like Unity as well. The Unity dock has great run-or-raise functionality, and the Compiz tiling plugin allows for some basic tiling placement.  Plus, all the indicators work well and very little configuration is needed.

I got a new 28" 4k monitor. Now that I can fit so much on a single screen, I thought I should try a tiling window manager to get the most of the out of the space. Linux HiDPI support still isn't great, but I'm still enjoying the experiment of trying out tiling.

Thanks again.

**Comment by gustavnikolaj** [comment]
Hey @markstos , have you had a chance to take it for a spin yet? :smile:

**Comment by markstos** [comment]
Yes, it worked for me. Thanks!

**Comment by gustavnikolaj** [comment]
I released 2.0.0 which includes just these changes. :-) Thanks for testing them out.
